language: python
stages:
  - lint
  - install

script:
  - echo "Scripts require visuals for now."

jobs:
  include:
    - python: 3.6
    - python: 3.7
    - stage: lint
      python: 3.7
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

    - stage: install
      python: 3.7
      install:
        - pip install --upgrade pip
        - pip install poetry
      script:
        - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
        - poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_existing: true
        skip_cleanup: true
