language: python
dist: xenial
sudo: true

stages:
  - lint
  - install
  - script
  - deploy

cache: pip

jobs:
  include:
    - python:
        - '3.6'
        - '3.7'
    - stage: lint
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files

    - stage: install
      install:
        - pip install --upgrade pip
        - pip install poetry
      script:
        - poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
        - poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_existing: true
        skip_cleanup: true

script:
  - echo "Skipping non-jobs"
